[package]
name = "general_repository"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.11.0", features = ["v4"] }
domain = { path = "../domain/" }
mockall = "0.13"
thiserror = "2.0.3"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "postgres"] }

